language: elixir

elixir:
    - 1.7
    - 1.8
    - 1.9

otp_release:
    - 20.3
    - 21.2
    - 22.0

script:
    - mix compile --warnings-as-errors
    - mix test
    - mix dialyzer --halt-exit-status

cache:
  directories:
    - _build
    - deps
